# Generated by Django 5.2.4 on 2026-08-01 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('yandex_metrika', 'Яндекс Метрика'), ('yandex_webmaster', 'Яндекс Вебмастер')], max_length=32)),
                ('retrieval_method', models.CharField(choices=[('synthetic', 'Синтетические данные')], default='synthetic', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('payload', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_source_snapshots', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_snapshots', to='projects.project')),
            ],
            options={
                'verbose_name': 'Снимок источника',
                'verbose_name_plural': 'Снимки источников',
                'ordering': ['-period_start', 'source'],
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_code', models.CharField(max_length=80)),
                ('numeric_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit', models.CharField(choices=[('count', 'Количество'), ('percent', 'Процент'), ('seconds', 'Секунды'), ('number', 'Число')], max_length=16)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='metrics.sourcesnapshot')),
            ],
            options={
                'verbose_name': 'Показатель',
                'verbose_name_plural': 'Показатели',
                'ordering': ['snapshot', 'metric_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='sourcesnapshot',
            constraint=models.UniqueConstraint(fields=('project', 'source', 'period_start', 'period_end'), name='unique_project_source_period'),
        ),
        migrations.AddIndex(
            model_name='metricpoint',
            index=models.Index(fields=['metric_code'], name='metric_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='metricpoint',
            constraint=models.UniqueConstraint(fields=('snapshot', 'metric_code'), name='unique_snapshot_metric_code'),
        ),
    ]
