# Generated by Django 5.2.4 on 2026-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metrics", "0003_rankingsnapshot_depth_and_api"),
    ]

    operations = [
        migrations.AddField(
            model_name="rankingsnapshot",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
