# Generated by Django 5.2.4 on 2026-08-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0004_rankingsnapshot_provenance"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcesnapshot",
            name="contains_sensitive_data",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourcesnapshot",
            name="provenance",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sourcesnapshot",
            name="retrieved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sourcesnapshot",
            name="sampling",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="sourcesnapshot",
            name="retrieval_method",
            field=models.CharField(
                choices=[
                    ("synthetic", "Синтетические данные"),
                    ("yandex_api", "API Яндекс Метрики"),
                ],
                default="synthetic",
                max_length=16,
            ),
        ),
    ]
