# Generated by Django 5.2.4 on 2026-08-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metrics", "0005_sourcesnapshot_contains_sensitive_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcesnapshot",
            name="retrieval_method",
            field=models.CharField(
                choices=[
                    ("synthetic", "Синтетические данные"),
                    ("yandex_api", "API Яндекса"),
                ],
                default="synthetic",
                max_length=16,
            ),
        ),
    ]
