# Generated by Django 5.2.4 on 2026-08-01

import uuid

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("domain", models.CharField(max_length=253, verbose_name="Домен")),
                (
                    "normalized_domain",
                    models.CharField(editable=False, max_length=253, unique=True),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Europe/Moscow", max_length=64, verbose_name="Часовой пояс"
                    ),
                ),
                ("language", models.CharField(default="ru", max_length=10, verbose_name="Язык")),
                ("active", models.BooleanField(default=True, verbose_name="Активен")),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectBrandRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("literal", "Строка"), ("regex", "Регулярное выражение")],
                        default="literal",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                ("pattern", models.CharField(max_length=500, verbose_name="Шаблон")),
                ("priority", models.IntegerField(default=0, verbose_name="Приоритет")),
                ("active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_rules",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Брендовое правило",
                "verbose_name_plural": "Брендовые правила",
                "ordering": ["-priority", "pattern"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUrlGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=200, verbose_name="Код"
                    ),
                ),
                ("priority", models.IntegerField(default=0, verbose_name="Приоритет")),
                ("active", models.BooleanField(default=True, verbose_name="Активна")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="url_groups",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL-группа",
                "verbose_name_plural": "URL-группы",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectUrlRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("starts_with", "Начинается с"),
                            ("contains", "Содержит"),
                            ("regex", "Регулярное выражение"),
                        ],
                        max_length=16,
                        verbose_name="Тип",
                    ),
                ),
                ("pattern", models.CharField(max_length=500, verbose_name="Шаблон")),
                ("priority", models.IntegerField(default=0, verbose_name="Приоритет")),
                ("active", models.BooleanField(default=True, verbose_name="Активно")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="projects.projecturlgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "URL-правило",
                "verbose_name_plural": "URL-правила",
                "ordering": ["-priority", "pattern"],
            },
        ),
        migrations.AddConstraint(
            model_name="projectbrandrule",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("pattern"),
                "project",
                "kind",
                name="unique_brand_rule_case_insensitive",
            ),
        ),
        migrations.AddConstraint(
            model_name="projecturlgroup",
            constraint=models.UniqueConstraint(
                fields=("project", "slug"), name="unique_project_url_group_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="projecturlrule",
            constraint=models.UniqueConstraint(
                fields=("group", "type", "pattern"), name="unique_group_url_rule"
            ),
        ),
    ]
