# Generated by Django 5.2.4 on 2026-08-09 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("topvisor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopvisorSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_month", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("success", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("loaded_keyword_count", models.PositiveIntegerField(default=0)),
                ("segments", models.JSONField(blank=True, default=list)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="topvisor.topvisorprojectmapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
