# Generated by Django 5.2.4 on 2026-08-12 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_top_11_20_mode"),
        ("topvisor", "0002_topvisorsyncrun"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopvisorConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(max_length=255, verbose_name="ID пользователя Topvisor"),
                ),
                ("api_key_encrypted", models.BinaryField()),
                (
                    "api_key_last_four",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                ("last_verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topvisor_connection",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подключение Topvisor",
                "verbose_name_plural": "Подключения Topvisor",
            },
        ),
    ]
