# Generated by Django 5.2.4 on 2026-10-07 21:34

import django.db.models.deletion
from django.db import migrations, models


def connect_existing_mappings(apps, schema_editor):
    TopvisorCredential = apps.get_model("topvisor", "TopvisorCredential")
    TopvisorProjectMapping = apps.get_model("topvisor", "TopvisorProjectMapping")
    credential = TopvisorCredential.objects.order_by("pk").first()
    if credential:
        TopvisorProjectMapping.objects.filter(topvisor_credential__isnull=True).update(
            topvisor_credential=credential
        )


class Migration(migrations.Migration):
    dependencies = [
        ("topvisor", "0004_global_topvisor_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="topvisorprojectmapping",
            name="topvisor_credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_mappings",
                to="topvisor.topvisorcredential",
                verbose_name="Аккаунт Topvisor",
            ),
        ),
        migrations.RunPython(connect_existing_mappings, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="topvisorcredential",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="topvisorcredential",
            name="user_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="ID пользователя Topvisor"
            ),
        ),
    ]
