# Generated by Django 5.2.4 on 2026-08-11 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_top_11_20_mode"),
        ("yandex", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="yandexconnection",
            name="scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="YandexWebmasterProjectMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_id", models.CharField(max_length=512)),
                ("host_url", models.URLField(max_length=2000)),
                ("verification_status", models.CharField(blank=True, max_length=64)),
                ("main_mirror", models.URLField(blank=True, max_length=2000)),
                ("domain_mismatch_confirmed", models.BooleanField(default=False)),
                (
                    "last_successful_sync_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webmaster_mappings",
                        to="yandex.yandexconnection",
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="yandex_webmaster_mapping",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="YandexWebmasterSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_month", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Выполняется"),
                            ("success", "Завершена"),
                            ("failed", "Ошибка"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mapping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="yandex.yandexwebmasterprojectmapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
