# Generated by Django 5.2.4 on 2026-08-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yandex", "0002_yandexconnection_scopes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="YandexOAuthCredential",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("client_id", models.CharField(max_length=255, verbose_name="ClientID")),
                ("client_secret_encrypted", models.BinaryField()),
                (
                    "client_secret_last_four",
                    models.CharField(blank=True, editable=False, max_length=4),
                ),
                ("redirect_uri", models.URLField(max_length=2000, verbose_name="Redirect URI")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Реквизиты OAuth Яндекса",
                "verbose_name_plural": "Реквизиты OAuth Яндекса",
            },
        ),
    ]
