# Generated by Django 5.2.4 on 2026-08-02 13:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0002_project_top_11_20_mode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_month", models.DateField(verbose_name="Отчётный месяц")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_month", "project__name"],
            },
        ),
        migrations.CreateModel(
            name="ReportVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["report", "-number"],
            },
        ),
        migrations.CreateModel(
            name="ReportDatasetSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_version", models.CharField(max_length=32)),
                ("formula_version", models.CharField(max_length=64)),
                ("payload", models.JSONField()),
                ("checksum", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot",
                        to="reports.reportversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ValidationIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=80)),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Предупреждение"), ("error", "Ошибка")],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="validation_issues",
                        to="reports.reportversion",
                    ),
                ),
            ],
            options={
                "ordering": ["severity", "code"],
            },
        ),
        migrations.AddConstraint(
            model_name="report",
            constraint=models.UniqueConstraint(
                fields=("project", "report_month"), name="unique_report_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="reportversion",
            constraint=models.UniqueConstraint(
                fields=("report", "number"), name="unique_report_version"
            ),
        ),
    ]
