# Generated by Django 5.2.4 on 2026-08-02 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdatasetsnapshot",
            name="version",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="snapshot",
                to="reports.reportversion",
            ),
        ),
    ]
