# Generated by Django 5.2.4 on 2026-08-02 14:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_reportdatasetsnapshot_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="validationissue",
            name="section_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name="NarrativeBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_code", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("deterministic", "Детерминированный"),
                            ("manual", "Ручной"),
                        ],
                        default="deterministic",
                        max_length=20,
                    ),
                ),
                ("generated_text", models.TextField(blank=True)),
                ("edited_text", models.TextField(blank=True)),
                ("facts", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generated", "Сформирован"),
                            ("edited", "Отредактирован"),
                            ("confirmed", "Подтверждён"),
                        ],
                        default="generated",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narrative_blocks",
                        to="reports.reportversion",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("report_version", "section_code", "sort_order"),
                        name="unique_narrative_block_order",
                    )
                ],
            },
        ),
    ]
