# Generated by Django 5.2.4 on 2026-08-02 18:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.reports.models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_validationissue_section_code_narrativeblock"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "artifact_type",
                    models.CharField(
                        choices=[("docx", "DOCX"), ("pdf", "PDF"), ("xlsx", "XLSX")],
                        max_length=8,
                    ),
                ),
                (
                    "profile",
                    models.CharField(default="full", editable=False, max_length=16),
                ),
                ("is_draft", models.BooleanField(default=False)),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=255,
                        upload_to=apps.reports.models.artifact_upload_to,
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                (
                    "generator_version",
                    models.CharField(default="mvp1.0", max_length=32),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Формируется"),
                            ("ready", "Готов"),
                            ("failed", "Ошибка"),
                        ],
                        default="generating",
                        max_length=16,
                    ),
                ),
                ("generation_log", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_artifacts",
                        to="reports.reportversion",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
