# Generated by Django 5.2.4 on 2026-08-01 23:06

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_categories', to='projects.project')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkLogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('work_date', models.DateField(verbose_name='Дата работы')),
                ('title', models.CharField(max_length=300, verbose_name='Работа')),
                ('status', models.CharField(choices=[('completed', 'Выполнено'), ('in_progress', 'В работе'), ('planned', 'Запланировано')], default='completed', max_length=16, verbose_name='Статус')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='URL страницы')),
                ('page_or_material_name', models.CharField(blank=True, max_length=300, verbose_name='Страница или материал')),
                ('character_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество знаков')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='Ответственный')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('result_url', models.URLField(blank=True, max_length=2000, verbose_name='Ссылка на результат')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='worklog.workcategory', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_worklog_items', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklog_items', to='projects.project')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненные работы',
                'ordering': ['-work_date', 'category__sort_order', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='workcategory',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('project'), name='unique_project_work_category_name'),
        ),
        migrations.AddConstraint(
            model_name='workcategory',
            constraint=models.UniqueConstraint(fields=('project', 'slug'), name='unique_project_work_category_slug'),
        ),
        migrations.AddIndex(
            model_name='worklogitem',
            index=models.Index(fields=['project', 'work_date'], name='worklog_project_date_idx'),
        ),
    ]
